### ISSUE TITLE
Javascript not hitting the OWA webserver

### ISSUE THREAD

**Issue by kabads** [Open-Web-Analytics/Open-Web-Analytics#524]
So I have installed this and created a profile for a site that I host on github. My OWA server sits behind a letsencrypt certificate (SSL). The script points to that domain, and DNS works (I have ssh'ed into a remote server and looked at the OWA server). However, when a page that has the javascript tracker is opened, I get no hits on the OWA webserver (in this case nginx). I would expect to see the browser make a request. What other things should I be checking for? 

Thanks in advance.

**Comment by padams** [comment]
Are you sure you included the tracking tag correctly in your pages?

**Comment by kabads** [comment]
That's a good point. The tag is there in the src of the html page, and it looks the same as the one that was provided by OWA - it is inside the body elements. So, apart from just inserting the tag in, I've not done anything specific with it, and didn't see anything in the documentation that said I should.

**Comment by padams** [comment]
The way to debug this is to open the inspector panel of your browser, reload the page and look at the network network requests and their http responses.

**Comment by kabads** [comment]
The http response was 200.

**Comment by Maaiins** [comment]
Looks like this one is solved, will closing this. Feel free to reopen if there is any trouble

**Comment by kabads** [comment]
So, this is the log from the nginx webserver that OWA is hosted on (from the tracker script), but the OWA console does not show that the visit being registered (the site is still not pushing any activity to OWA).

**Comment by Maaiins** [comment]
Try to activate logging in `owa-config.php` and take a look into log file `owa-data/logs`

To activate logging uncomment `define('OWA_ERROR_HANDLER', 'development');`

**Comment by kabads** [comment]
So, with the console open when the site that has the tracker on, I get this error:

`Loading failed for the <script> with source “https://home.my-site.org/owa/modules/base/js/owa.tracker-combined-min.js”.`

This site is hosted by github - that shouldn't cause a problem, should it? If I click that link (in the console error), it opens the javascript on the OWA site (in the browser).

**Comment by Maaiins** [comment]
Do you have adblocker or noscript installed and activated in your Browser?

**Comment by kabads** [comment]
OK - Thanks @Maaiins - an adblocker was to blame for the javascript error. I'm still having problems. I have enabled the error logs, and there is a lot there. I really can't find anything that looks bad, apart from a bit where it cannot find the cache file:

`12:58:43 2020-04-11 16809 [debug_log] About to perform action: base.reportDashboard
12:58:43 2020-04-11 16809 [debug_log] Performing Action: owa_reportDashboardController
12:58:43 2020-04-11 16809 [debug_log] Getting state - store: u key:
12:58:43 2020-04-11 16809 [debug_log] Getting state - store: p key:
12:58:43 2020-04-11 16809 [debug_log] loading last value in initial state container for store: p
12:58:43 2020-04-11 16809 [debug_log] populating state for store: p, name: , value: b8e7a27d633052b4cc847db0d1bd931d91928af95417bb9afe83a3a63c85d427, store type: cookie, is_perm:
12:58:43 2020-04-11 16809 [debug_log] Getting state - store: u key:
12:58:43 2020-04-11 16809 [debug_log] Getting state - store: p key:
12:58:43 2020-04-11 16809 [debug_log] check cache file: /var/www/html/owa/owa-data/caches/1/owa_user/d819f11dc6a3ab4876f49154435babb8.php
12:58:43 2020-04-11 16809 [debug_log] Cache File not found for Collection: owa_user, id: d819f11dc6a3ab4876f49154435babb8, file: /var/www/html/owa/owa-data/caches/1/owa_user/d819f11dc6a3ab4876f49154435babb8.php
12:58:43 2020-04-11 16809 [debug_log] CACHE MISS - object not found for Collection: owa_user, id: d819f11dc6a3ab4876f49154435babb8
12:58:43 2020-04-11 16809 [debug_log] Col: user_id, value: adam
12:58:43 2020-04-11 16809 [debug_log] Query: SET SESSION sql_mode=''`

**Comment by Maaiins** [comment]
I think that´s not the problem.
Next step is to verify that owa.tracker is submitting some data.

Open network tab in your the browser dev tools. Make sure to do something like "preserve log" this will keep the requests when you click some links.

Do some interactions with your site, and take a look into network tab. There must be some post request to `blank.php` or `log.php`

When there are no requests, please post your owa.tracker implementation here

**Comment by kabads** [comment]
Hmm - I'm not seeing anything in the network tab about blank.php or log.php - this is the javascript code snippet that was produced by the OWA server:

```
<!-- Start Open Web Analytics Tracker -->
<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'http://home.monkeez.org/owa/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', '9756fd0e111e54bbe693ed980033c8d9']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);

(function() {
	var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
	owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
	_owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
	var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>
</script>
<!-- End Open Web Analytics Code --> 
```

**Comment by Maaiins** [comment]
Hm strange behavior...

Two things:

Is the Site Id correct?

Try to change your owa_baseUrl to https
`var owa_baseUrl = 'https://home.my-site.org/owa/';`

**Comment by Maaiins** [comment]
> Hm strange behavior...
> 
> Two things:
> 
> Is the Site Id correct?
> 
> Try to change your owa_baseUrl to https
> `var owa_baseUrl = 'https://home.my-site.org/owa/';`

I took a look into your git repo and found the site you are using owa. The console outputs the following error: https://home.my-site.org/owa/modules/base/js/owa.tracker-combined-min.js net::ERR_CONNECTION_TIMED_OUT

Is the subdomain reachable? I cant open the tracker.js when i open the url in my browser

**Comment by kabads** [comment]
Thankyou so much @Maaiins - I had a network issue, where I was only accepting traffic on port 80 and not 443 - this is since fixed and now the OWA logs shows more of a problem. 

`12-Apr-2020 05:02:20 America/Los_Angeles] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/owa/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/owa/modules/base/classes/browscap.php on line 20
`
Thankyou for your patience.

**Comment by Maaiins** [comment]
Ah you didn´t used the packaged owa from release.

Please take a look to and download the packaged.tar:
https://github.com/Open-Web-Analytics/Open-Web-Analytics/releases

or read this
https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installing-from-Github

**Comment by kabads** [comment]
Many thanks - it works. I thought I could download the source code. However, since downloading from github and using the composer command it works.
